name: Laravel Food Ordering

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        # run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      - name: Run Static Analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon

      # - name: Run Style Check
      #   run: vendor/bin/phpcs --standard=PSR12 app/

      # - name: Run Security Checker
      #   run: vendor/bin/security-checker security:check composer.lock

      # - name: Run Deprecation Checker
      # #   run: vendor/bin/deprecation-detector detect:run src/

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=7 --memory-limit=2G

      # - name: Upload Code Coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./storage/logs/coverage.xml
      #     fail_ci_if_error: true
      #     verbose: true
      #     flags: unittests
      #     name: codecov-umbrella-laravel-foor-ordering

      # 🔔 Slack notification on test failure
      - name: Notify Slack (Tests Failed)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"❌ CI Tests Failed\nProject: Laravel Food Ordering\nBranch: ${{ github.ref_name }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # 🔔 Slack notification on test success
      - name: Notify Slack (Tests Passed)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"✅ CI Tests Passed for Laravel Food Ordering (Branch: ${{ github.ref_name }})\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            cd ${{ secrets.APP_PATH }} || { echo "Path not found: ${{ secrets.APP_PATH }}"; exit 1; }
            bash deploy.sh || { echo "Deployment script failed"; exit 1; }

      # 🔔 Slack notification on deployment failure
      - name: Notify Slack (Deployment Failed)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"❌ Deployment Failed\nProject: Laravel Instgram Ordering\nBranch: ${{ github.ref_name }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # 🔔 Slack notification on deployment success
      - name: Notify Slack (Deployment Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"✅ Deployment Successful for Laravel Instgram Ordering\nBranch: ${{ github.ref_name }}\nEnvironment: Production\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
